### ISSUE TITLE
Question: XDP Director status

### ISSUE THREAD

**Issue by bgmerrell** [github/glb-director#119]
Hi, I'm seeing commits in 2020 for the XDP director, which I think is super exciting! We're interested in using GLB Director in a large e-commerce environment, but I haven't seen any official announcements regarding the XDP director's availability. Before getting to deep into the XDP director, I was hoping to get idea of its status. Is it being run in production? are there any pending features? known bugs? etc.  Thanks so much!

(Sorry, if this isn't the right forum for a question like this, but I didn't see any contact/chat info and I saw some precedence for questions in other GitHub issues)

**Comment by theojulienne** [comment]
Over at GitHub we have it running in testing clusters but haven't quite yet rolled it out to production traffic. A few folks in issues here have been working with it, but I'm not sure if they have it in production.

It's been designed to be close to 1:1 compatible with the DPDK version and I'd love to get it over the line and seeing production traffic, both at GitHub and anywhere else, I think XDP is definitely the future for load balancers of this type. It should be very close to production quality for most purposes/configurations supported, it passes the same tests as the DPDK version and with XDP JIT enabled in a previous benchmark and testing internally it does perform at least as well as the DPDK version too (both capped out at 10G line rate on our production NICs).

**Comment by bgmerrell** [comment]
@theojulienne Thanks for the information, that is all super helpful. It's cool to see the Vagrant example setup and tests, too. I'll start playing with those.  I'll close this issue to get it out of the way, but it would be really great to see some "press" (blogs, conference talk, etc) when GitHub starts using the XDP director in production. I'd love to hear from anyone else's production experiences, too. Thanks again!

**Comment by bgmerrell** [comment]
> I think XDP is definitely the future for load balancers of this type.

+1 btw :)
