### ISSUE TITLE
Question about filling state

### ISSUE THREAD

**Issue by maxstr** [github/glb-director#123]
Hi there, 

First off, many thanks for this project and making it public. It's quite interesting and valuable to outsiders.

I was wondering when/how it is decided a proxy node is no longer in the filling state and is transitioned to the active state. With a proxy that is draining it is safe to remove once it is no longer handling any connections, which makes sense. But for a proxy that is filling it may be passing some traffic to its secondary for an indeterminate period of time. Is there an easy way to tell that a node is no longer handling any traffic for the secondary or do you just make an assumption it is not after not having seen such traffic for some period of time?

**Comment by theojulienne** [comment]
> I was wondering when/how it is decided a proxy node is no longer in the filling state and is transitioned to the active state.

Great question! At GitHub, we specify an SLO on the expectation of how long connections should be able to continue under normal operations, based on the cluster (internal vs public). We then move nodes through states once this time elapses.

**Comment by maxstr** [comment]
> > I was wondering when/how it is decided a proxy node is no longer in the filling state and is transitioned to the active state.
> 
> Great question! At GitHub, we specify an SLO on the expectation of how long connections should be able to continue under normal operations, based on the cluster (internal vs public). We then move nodes through states once this time elapses.

Got it, makes sense. Thanks for the response!
