### ISSUE TITLE
Remove Ubuntu specific hacks

### ISSUE THREAD

**Issue by lmb** [github/glb-director#32]
`glb-redirect` has some sort of compatibility hack in it's source: https://github.com/github/glb-director/blob/master/src/glb-redirect/libxt_GLBREDIRECT.c#L25-L27

This breaks building on arm64 which I'm currently looking into. Are these hacks still required? Is it possible to gate them just to Ubuntu?

**Comment by lmb** [comment]
@theojulienne do you have any insight on this?

**Comment by theojulienne** [comment]
Sorry for the delay here!

:+1: Since Precise is EOL, I think it's reasonable to remove those special cases. I've filed https://github.com/github/glb-director/pull/36 to remove them.

Did you find removing those lines was enough to get it to compile on arm64?

**Comment by lmb** [comment]
Yup, that made it compile at least. I haven't gotten around to testing it 
on arm.
