### ISSUE TITLE
Using the glb Wireshark dissector doesn't work out of the box

### ISSUE THREAD

**Issue by lmb** [github/glb-director#41]
Hi,

I did the naive thing and copied the contents of the glb dissector directory to `~/.config/wireshark/plugins/glb-...`, but Wireshark then complains that it can't find `glb_fou.lua`. It seems like the dissector expects that file to be in `~`?

I've fixed that by just moving `gue_fou.lua` to `init.lua`, but that seems like a hack.

**Comment by theojulienne** [comment]
Ah, interesting. I was putting `init.lua` and `gue_fou.lua` from `src/glb-wireshark-dissector` in `~/.wireshark`. It would be great if there was a nicer way to do it in a plugin.

**Comment by lmb** [comment]
I think if you just ship a single `init.lua` it works when sticking the directory under `.config/wireshark/plugins`.
