### ISSUE TITLE
Unable to locate package glb-director

### ISSUE THREAD

**Issue by Mikedu1988** [github/glb-director#57]
tried the command in document, on ubuntu 14, get Unable to locate package glb-director error.

![image](https://user-images.githubusercontent.com/24424690/52989362-ff286e80-343d-11e9-936e-b7700975dd88.png)

**Comment by 19Gautham** [comment]
I am facing the same problem. @Mikedu1988 have you found a solution?

**Comment by 19Gautham** [comment]
Apologies. Didn't notice it has been released only for debian at the moment.
