### ISSUE TITLE
haproxy still in use?

### ISSUE THREAD

**Issue by git001** [github/glb-director#65]
The both blog posts describe how the glb is setuped and which components are in use 

https://github.blog/2016-09-22-introducing-glb/  
https://github.blog/2016-12-01-glb-part-2-haproxy-zero-downtime-zero-delay-reloads-with-multibinder/  

Is the current glb still the same as described in the blog posts?

**Comment by theojulienne** [comment]
Yep, we still use HAProxy behind glb-director. With HAProxy 1.8+, seamless reloads are now supported using the master-worker model, so multibinder isn't needed.

**Comment by git001** [comment]
Thanks for clarification.
