### ISSUE TITLE
Vagrant setup issue

### ISSUE THREAD

**Issue by hanlins** [github/glb-director#86]
Got errors running `vagrant up` command, the cause is that `linux-herader-4.9.0-9-amd64` package is deprecated. Here's the error logs on my local environment:

```
...
==> router: Checking for guest additions in VM...
    router: No guest additions were detected on the base box for this VM! Guest
    router: additions are required for forwarded ports, shared folders, host only
    router: networking, and more. If SSH fails on this machine, please install
    router: the guest additions and repackage the box to continue.
    router:
    router: This is not an error message; everything may continue to work properly,
    router: in which case you may ignore this message.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20190801T025637Z/ stretch main
apt-get install -y linux-headers-`uname -r` dkms

Stdout from the command:

Reading package lists...
Building dependency tree...
Reading state information...


Stderr from the command:

E: Unable to locate package linux-headers-4.9.0-9-amd64
E: Couldn't find any package by glob 'linux-headers-4.9.0-9-amd64'
E: Couldn't find any package by regex 'linux-headers-4.9.0-9-amd64'
```

Workaround:
The error is actually caused by `vagrant-vbguest` plugin since it's also installing that [linux header package](https://github.com/dotless-de/vagrant-vbguest/blob/f5442fcf85b76e5af66a616d592314c78380a77d/lib/vagrant-vbguest/installers/debian.rb#L35)

What I did is to uninstall that plugin locally
```
vagrant plugin uninstall vagrant-vbguest
```

Then add the source list in the box (following this [workaround](https://github.com/dotless-de/vagrant-vbguest/issues/351#issuecomment-538096696)).

**Comment by ravisinghsfbay** [comment]
The debian/stretch64 box was built for Linux kernel 4.9.0.9.
Kernel headers for that version are no longer available in the apt repos.

Here is a Debian9 box built with kernel version 4.9.0.11. I have been using this and it works fine as far as I can tell.
https://app.vagrantup.com/ravisinghsfbay/boxes/debian_stretch64_4.9.0-11-amd64/versions/0

**Comment by k4tsh** [comment]
> The debian/stretch64 box was built for Linux kernel 4.9.0.9.
> Kernel headers for that version are no longer available in the apt repos.
> 
> Here is a Debian9 box built with kernel version 4.9.0.11. I have been using this and it works fine as far as I can tell.
> https://app.vagrantup.com/ravisinghsfbay/boxes/debian_stretch64_4.9.0-11-amd64/versions/0

Expanding on this, just to be explicit in instruction, what worked for me is replacing line 5 in [Vagrantfile](https://github.com/github/glb-director/blob/master/Vagrantfile), `config.vm.box = "debian/stretch64"` with: 

```
config.vm.box = "ravisinghsfbay/debian_stretch64_4.9.0-11-amd64"
config.vm.box_version = "0"
```

With that, running `script/cibuild` succeeded with no issue.

**Comment by llsousa** [comment]
Probably this issue is already solved. Please see https://github.com/dotless-de/vagrant-vbguest/issues/351#issuecomment-592098634?

**Comment by mcarbonneaux** [comment]
i've similar issue...

i'm on ubuntu 20.04 with vagrant 2.2.6 with libvirt.

When launch script/cibuild i get this error:

```
Step 13/16 : RUN apt-get update && apt install -y -t stretch-backports linux-image-amd64 linux-headers-amd64 iproute2 libbpf-dev linux-libc-dev
 ---> Running in 19a98997a472
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Hit:2 http://ftp.debian.org/debian stretch-backports InRelease
Ign:3 http://deb.debian.org/debian stretch InRelease
Hit:4 http://deb.debian.org/debian stretch-updates InRelease
Hit:5 http://deb.debian.org/debian stretch Release
Hit:7 https://packagecloud.io/github/unofficial-dpdk-stable/debian stretch InRelease
Fetched 94.3 kB in 1s (60.8 kB/s)
Reading package lists...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 linux-image-amd64 : Depends: linux-image-4.19.0-0.bpo.8-amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt install -y -t stretch-backports linux-image-amd64 linux-headers-amd64 iproute2 libbpf-dev linux-libc-dev' returned a non-zero code: 100
```

they try to install `linux-image-4.19.0-0.bpo.8-amd64` ...
